apiVersion: apps/v1
kind: Deployment
metadata:
  name: cities-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citiesservice
  template:
    metadata:
      labels:
        app: citiesservice
    spec:
      containers:
        - name: citiesservice
          image: dviradani/citiesservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: cities-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: citiesservice
  ports:
    - name: citiesservice
      protocol: TCP
      port: 80
      targetPort: 80
    - name: citiesgrpc
      protocol: TCP
      port: 666
      targetPort: 666
